Task3

From Bank DataSet:
    
1.Dealing with missing values.

2.Check for duplicates if exist.

3.Go on your work by cleaning the duration column.

4.Show the table of the previous question 
after sorting it by duration

In [1]:
import pandas as pd

In [2]:
bank_df = pd.read_csv("Bank_Customer.csv")

In [5]:
bank_df.isna().sum()

age          90
job           0
marital       0
education     0
balance       0
duration      0
dtype: int64

In [21]:
bank_df.fillna(bank_df.mean(),inplace = True)

C:\Users\user\AppData\Local\Temp\ipykernel_22460\120744293.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  bank_df.fillna(bank_df.mean(),inplace = True)

In [22]:
bank_df.duplicated().sum()

0

In [23]:
bank_df["duration"].unique()

array([2.61000000e+02, 1.51000000e+02, 7.60000000e+01, 9.20000000e+01,
       1.98000000e+02, 1.39000000e+02, 2.17000000e+02, 3.80000000e+02,
       5.00000000e+01, 5.50000000e+01, 2.22000000e+02, 1.37000000e+02,
       5.17000000e+02, 7.10000000e+01, 1.74000000e+02, 3.53000000e+02,
       9.80000000e+01, 3.80000000e+01, 2.19000000e+02, 5.40000000e+01,
       2.62000000e+02, 1.64000000e+02, 1.60000000e+02, 3.42000000e+02,
       1.81000000e+02, 1.72000000e+02, 2.96000000e+02, 1.27000000e+02,
       2.55000000e+02, 3.48000000e+02, 2.25000000e+02, 2.30000000e+02,
       2.08000000e+02, 2.26000000e+02, 3.36000000e+02, 2.42000000e+02,
       3.65000000e+02, 1.66600000e+03, 5.77000000e+02, 1.80000000e+02,
       2.20000000e+01, 1.49200000e+03, 6.16000000e+02, 3.55000000e+02,
       3.63000000e+02, 2.66000000e+02, 2.53000000e+02, 1.79000000e+02,
       7.87000000e+02, 1.45000000e+02, 1.04000000e+02, 1.30000000e+01,
       1.85000000e+02, 1.77800000e+03, 1.38000000e+02, 8.12000000e+02,
       3.91000000e+02, 3.57000000e+02, 9.10000000e+01, 5.28000000e+02,
       2.73000000e+02, 1.58000000e+02, 1.77000000e+02, 2.58000000e+02,
       1.54000000e+02, 2.91000000e+02, 1.76000000e+02, 2.11000000e+02,
       3.49000000e+02, 2.72000000e+02, 1.93000000e+02, 2.12000000e+02,
       2.00000000e+01, 1.04200000e+03, 2.46000000e+02, 5.29000000e+02,
       1.46700000e+03, 1.38900000e+03, 1.88000000e+02, 4.80000000e+01,
       2.13000000e+02, 5.83000000e+02, 2.21000000e+02, 1.73000000e+02,
       4.26000000e+02, 2.87000000e+02, 1.01000000e+02, 2.03000000e+02,
       1.97000000e+02, 2.57000000e+02, 1.24000000e+02, 2.29000000e+02,
       4.00000000e+02, 1.90000000e+02, 2.10000000e+01, 5.14000000e+02,
       8.49000000e+02, 2.71749306e+02, 1.44000000e+02, 2.86000000e+02,
       1.07000000e+02, 2.47000000e+02, 5.18000000e+02, 3.64000000e+02,
       1.78000000e+02, 4.39000000e+02, 7.90000000e+01, 1.20000000e+02,
       1.75000000e+02, 6.10000000e+01, 7.80000000e+01, 1.43000000e+02,
       5.79000000e+02, 6.77000000e+02, 3.45000000e+02, 1.00000000e+02,
       1.25000000e+02, 1.36000000e+02, 7.30000000e+01, 5.41000000e+02,
       1.63000000e+02, 3.01000000e+02, 4.60000000e+01, 2.04000000e+02,
       1.57000000e+02, 2.43000000e+02, 1.86000000e+02, 6.10000000e+02,
       2.03300000e+03, 8.50000000e+01, 1.14000000e+02, 5.70000000e+01,
       2.38000000e+02, 9.30000000e+01, 1.28000000e+02, 3.03000000e+02,
       5.58000000e+02, 2.70000000e+02, 2.28000000e+02, 9.90000000e+01,
       2.40000000e+02, 6.73000000e+02, 2.33000000e+02, 1.05600000e+03,
       2.50000000e+02, 2.52000000e+02, 1.30000000e+02, 4.12000000e+02,
       1.90000000e+01, 4.58000000e+02, 7.17000000e+02, 3.13000000e+02,
       6.83000000e+02, 1.07700000e+03, 4.16000000e+02, 1.46000000e+02,
       1.67000000e+02, 3.15000000e+02, 1.40000000e+02, 3.46000000e+02,
       5.62000000e+02, 1.42000000e+02, 6.70000000e+01, 3.09000000e+02,
       2.48000000e+02, 2.56000000e+02, 8.20000000e+01, 4.77000000e+02,
       6.11000000e+02, 4.71000000e+02, 3.81000000e+02, 4.20000000e+01,
       2.51000000e+02, 4.08000000e+02, 2.15000000e+02, 2.16000000e+02,
       3.66000000e+02, 2.10000000e+02, 2.88000000e+02, 1.68000000e+02,
       3.38000000e+02, 4.10000000e+02, 3.00000000e+02, 1.41900000e+03,
       2.70000000e+01, 1.80000000e+01, 7.30000000e+02, 7.46000000e+02,
       1.21000000e+02, 4.00000000e+01, 2.06000000e+02, 3.89000000e+02,
       7.02000000e+02, 1.17000000e+02, 2.32000000e+02, 3.90000000e+01,
       2.82000000e+02, 7.14000000e+02, 2.27000000e+02, 1.19000000e+02,
       3.61000000e+02, 3.50000000e+02, 3.32000000e+02, 1.13000000e+02,
       1.32000000e+02, 5.80000000e+01, 8.90000000e+01, 1.52000000e+02,
       1.10000000e+02, 4.63000000e+02, 9.62000000e+02, 1.00000000e+01,
       1.18000000e+02, 1.89000000e+02, 2.34000000e+02, 7.50000000e+01,
       6.21000000e+02, 3.10000000e+02, 1.56000000e+02, 5.00000000e+00,
       2.00000000e+00, 7.42000000e+02, 3.62000000e+02, 2.00000000e+02,
       1.26000000e+02, 6.50000000e+01, 2.67000000e+02, 2.09000000e+02,
       2.05000000e+02, 8.30000000e+01, 1.06000000e+02, 1.05000000e+02,
       1.08000000e+02, 3.11000000e+02, 2.14000000e+02, 3.58000000e+02,
       4.53000000e+02, 3.86000000e+02, 2.41000000e+02, 2.24000000e+02,
       1.48000000e+02, 1.96000000e+02, 1.11000000e+02, 2.31000000e+02,
       3.16000000e+02, 4.25000000e+02, 1.35000000e+02, 4.02000000e+02,
       1.83000000e+02, 3.25000000e+02, 5.03000000e+02, 9.50000000e+01,
       6.80000000e+02, 4.21000000e+02, 8.08000000e+02, 1.95000000e+02,
       3.47000000e+02, 4.04000000e+02, 3.96000000e+02, 8.80000000e+01,
       3.79000000e+02, 1.02000000e+02, 3.06000000e+02, 2.18000000e+02,
       3.44000000e+02, 6.52000000e+02, 1.84000000e+02, 2.35000000e+02,
       2.90000000e+02, 1.33000000e+02, 3.18000000e+02, 2.60000000e+02,
       4.37000000e+02, 5.01000000e+02, 1.20100000e+03, 1.03000000e+03,
       1.49000000e+02, 7.69000000e+02, 1.99000000e+02, 4.24000000e+02,
       4.30000000e+01, 3.26000000e+02, 3.93000000e+02, 4.83000000e+02,
       2.59000000e+02, 5.76000000e+02, 9.00000000e+01, 5.05000000e+02,
       2.45000000e+02, 6.23000000e+02, 4.96000000e+02, 2.76000000e+02,
       8.70000000e+01, 7.44000000e+02, 7.65000000e+02, 1.50000000e+02,
       1.12000000e+02, 2.78000000e+02, 1.62300000e+03, 3.54000000e+02,
       1.87000000e+02, 4.51000000e+02, 1.59000000e+02, 4.09000000e+02,
       1.70000000e+02, 6.08000000e+02, 5.30000000e+01, 1.34000000e+02,
       6.78000000e+02, 1.82000000e+02, 1.62000000e+02, 6.99000000e+02,
       9.70000000e+01, 1.67700000e+03, 2.83000000e+02, 3.23000000e+02,
       4.70000000e+01, 3.00000000e+01, 4.72000000e+02, 4.48000000e+02,
       2.64000000e+02, 1.69000000e+02, 3.37000000e+02, 3.74000000e+02,
       5.31000000e+02, 1.53000000e+02, 8.00000000e+01, 9.18000000e+02,
       2.69000000e+02, 3.71000000e+02, 4.27000000e+02, 6.04000000e+02,
       2.63000000e+02, 1.29000000e+02, 1.91000000e+02, 2.60000000e+01,
       2.89000000e+02, 1.23000000e+02, 1.61000000e+02, 2.68000000e+02,
       3.83000000e+02, 4.40000000e+02, 2.30000000e+01, 1.29700000e+03,
       6.90000000e+01, 5.24000000e+02, 9.60000000e+01, 1.55000000e+02,
       3.52000000e+02, 3.90000000e+02, 3.69000000e+02, 3.41000000e+02,
       5.26000000e+02, 3.60000000e+01, 1.90600000e+03, 1.47000000e+02,
       4.07000000e+02, 3.39000000e+02, 2.85000000e+02, 7.03000000e+02,
       8.02000000e+02, 3.04000000e+02, 3.92000000e+02, 2.01000000e+02,
       3.28000000e+02, 1.16000000e+02, 2.93000000e+02, 3.70000000e+01,
       5.30000000e+02, 2.90000000e+01, 3.12000000e+02, 2.84000000e+02,
       5.07000000e+02, 6.84000000e+02, 3.33000000e+02, 3.22000000e+02,
       2.02000000e+02, 7.39000000e+02, 3.08000000e+02, 4.67000000e+02,
       3.20000000e+02, 6.40000000e+01, 3.78000000e+02, 1.59700000e+03,
       6.00000000e+01, 1.09000000e+02, 3.10000000e+01, 5.93000000e+02,
       6.31000000e+02, 3.20000000e+01, 1.52900000e+03, 2.54000000e+02,
       3.14000000e+02, 5.97000000e+02, 2.07000000e+02, 3.05000000e+02,
       1.22000000e+02, 6.60000000e+01, 3.43000000e+02, 5.90000000e+01,
       2.49000000e+02, 4.06000000e+02, 2.20000000e+02, 5.10000000e+01,
       2.75000000e+02, 4.79000000e+02, 3.50000000e+01, 7.20000000e+02,
       7.00000000e+01, 1.41000000e+02, 3.95000000e+02, 6.29000000e+02,
       5.02000000e+02, 4.46000000e+02, 1.31000000e+02, 2.92000000e+02,
       6.80000000e+01, 8.52000000e+02, 9.23000000e+02, 9.53000000e+02,
       2.94000000e+02, 7.40000000e+01, 5.20000000e+02, 1.71000000e+02,
       4.85000000e+02, 7.32000000e+02, 3.59000000e+02, 1.52100000e+03,
       8.00000000e+02, 6.15000000e+02, 3.27000000e+02, 2.36000000e+02,
       4.92000000e+02, 2.98000000e+02, 1.13800000e+03, 5.91000000e+02,
       7.86000000e+02, 1.92000000e+02, 3.88000000e+02, 4.01000000e+02,
       4.35000000e+02, 2.23000000e+02, 4.23000000e+02, 6.34000000e+02,
       7.99000000e+02, 4.44000000e+02, 5.66000000e+02, 2.74000000e+02,
       4.90000000e+01, 3.76000000e+02, 8.66000000e+02, 5.60000000e+01,
       1.58100000e+03, 2.79000000e+02, 4.32000000e+02, 5.16000000e+02,
       6.14000000e+02, 6.50000000e+02, 7.20000000e+01, 4.74000000e+02,
       5.59000000e+02, 1.10100000e+03, 9.12000000e+02, 6.90000000e+02,
       3.29000000e+02, 1.06200000e+03, 6.88000000e+02, 1.03000000e+02,
       1.94000000e+02, 6.07000000e+02, 3.98000000e+02, 4.81000000e+02,
       2.17700000e+03, 4.18000000e+02, 9.40000000e+01, 4.41000000e+02,
       1.65000000e+02, 7.64000000e+02, 2.97000000e+02, 1.27300000e+03,
       1.57400000e+03])

In [24]:
import numpy as np
bank_df["duration"] = pd.to_numeric(bank_df["duration"],errors = 'coerce')

In [25]:
bank_df["duration"]= bank_df["duration"].astype(int)

In [26]:
sorted_df = bank_df.sort_values(by = "duration")

In [27]:
print(sorted_df)

         age          job  marital  education  balance  duration
287   50.000   technician   single   tertiary      339         2
284   30.000  blue-collar   single  secondary        0         5
272   57.000   technician  married  secondary     1078        10
538   34.000  blue-collar  married    unknown      245        13
706   44.000   technician   single    unknown       78        13
...      ...          ...      ...        ...      ...       ...
474   34.000       admin.  married  secondary      869      1677
59    46.000     services  married    primary      179      1778
600   38.000  blue-collar  married  secondary      384      1906
152   40.000   management  married   tertiary       -4      2033
1034  42.582  blue-collar   single  secondary      277      2177

[1090 rows x 6 columns]